### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by vladikoff** [comment]
@coalman Hey, could you merge this or give me maintainers rights for this plugin please?

Thanks!

**Comment by tclindner** [comment]
Hi @coalman would you be willing to take @vladikoff up on his offer? htmllint is a nice tool and we would like to use it with Grunt 1+ :)

**Comment by Bufallo** [comment]
Any news on this?
htmllint is the last of my dependencies not compatible to grunt 1+.
I love htmllint;-)

**Comment by jitendravyas** [comment]
Hi @mlochbaum Can you check this PR?

**Comment by mlochbaum** [comment]
Updated in v0.3.0

**Pull request closed without merging**
